packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.8.2
  "@trpc/server": ^11.5.0
  better-auth: ^1.4.5
  ai: ^5.0.49
  "@ai-sdk/google": ^2.0.13
  dotenv: ^17.2.2
  "@trpc/tanstack-react-query": ^11.5.0
  "@trpc/client": ^11.5.0
  "@tanstack/react-query": ^5.85.5
  "@ai-sdk/react": ^2.0.39
  "@better-auth/expo": ^1.4.5
  drizzle-orm: ^0.44.2
